### ISSUE TITLE
Flexbox Layout module

### ISSUE THREAD

**Issue by NickToye** [inuitcss/CONTRIBUTING#26] opened 2016-06-13 22:35 UTC
This is something I was considering adding into my own project, any reason why I shouldn't?

**Comment by csshugs** [comment] 2016-06-14 07:12
@NickToye 

> any reason why I shouldn't?

**Short answer:** No.

**Long answer:** If you find yourself needing a layout module built with flexbox, go ahead. 
In other words: I use the standard layout module, because a flexbox version would not offer me some enhancement, which would be useful to me, except that you won't need the HTML-comments anymore. But if you need something like layout items which have all the same height (per row), flexbox would be a good choice to achieve this. [I built an extension myself](https://github.com/csshugs/objects.flex-layout) for exact this behaviour.

**Comment by anselmh** [comment] 2016-06-22 12:09
Marking this as a duplicate of https://github.com/inuitcss/CONTRIBUTING/issues/20.

**Closed as completed by anselmh** 2016-06-22 12:09 UTC
Labels: duplicate

**Comment by NickToye** [comment] 2016-06-28 23:57
thanks.
